Feature/bi 2165
Breeding-Insight/taf pull request #141
Opened 2024-07-10 06:59 UTC by cvacalares

# Description
Add test for BI-2165.

# Testing
[_Please include a link to a successful run of TAF for this change_](https://github.com/Breeding-Insight/taf/actions/runs/9852832645)

# Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation

2024-07-10 22:19 UTC, HMS17 requested changes
GermplasmImportDuplicateGIDs.feature seems to be setup steps initially created for sample upload but with any Then statements removed in a later commit. Is there still a purpose for it?

Also since this card does a lot more than just adding steps/features/selectors for sorting, it might be good for documentation and clarity to mention in the description the driver updates and adding step definitions for sample submission upload, and changing Name to Germplasm Name.

2024-07-16 21:47 UTC, cvacalares commented
> GermplasmImportDuplicateGIDs.feature seems to be setup steps initially created for sample upload but with any Then statements removed in a later commit. Is there still a purpose for it? --> Not sure if I understand what's your request. I'm following the way the test was described in the ticket. I try to fill in some steps if they are not clear or vague.

> 
> Also since this card does a lot more than just adding steps/features/selectors for sorting, it might be good for documentation and clarity to mention in the description the driver updates and adding step definitions for sample submission upload, and changing Name to Germplasm Name. --> Sure, I'll do that next time. The commits I did contains those comments.

2024-07-24 14:50 UTC, dmeidlin approved these changes

2024-07-25 21:05 UTC, HMS17 approved these changes

2024-07-29 22:55 UTC, merged