Add test for BI-2057.
Breeding-Insight/taf pull request #147
Opened 2024-08-30 06:57 UTC by cvacalares

# Description
BI-2057

Add page for Sample Management.
Add steps for Sample Management.

# Dependencies
_Please include any dependencies to other code branches, testing configurations, scripts to be run, etc._

# Testing
[_Please include a link to a successful run of TAF for this change_](https://github.com/Breeding-Insight/taf/actions/runs/10610039421)

# Checklist:

- [ x] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation

2024-09-04 15:03 UTC, cvacalares commented
Still working on it.

2024-09-04 18:11 UTC, nickpalladino approved these changes

2024-09-06 05:21 UTC, cvacalares commented
@davedrp - i have included the genotype samples. please review. thanks.

2024-09-06 17:09 UTC, davedrp requested changes

2024-09-10 05:16 UTC, cvacalares commented on src/features/BI-2057.feature
> +    When user selects "Experiments & Observations" in navigation
@davedrp - Done. thanks.

2024-09-12 14:18 UTC, davedrp approved these changes

2024-09-20 05:12 UTC, merged