Feature/bi 2056
Breeding-Insight/taf pull request #149
Opened 2024-09-11 00:13 UTC by cvacalares

# Description
BI-2056 - The ontology can be case insensitive
Add step definition for clicking a row of an Ontology.

# Testing
[_Please include a link to a successful run of TAF for this change_](https://github.com/Breeding-Insight/taf/actions/runs/10787725833)

# Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation

2024-09-12 14:16 UTC, davedrp requested changes

2024-09-20 05:44 UTC, cvacalares commented
@davedrp 
Don't you need a Germplasm entry before you can do a Experiments and Observation?
![image](https://github.com/user-attachments/assets/3f22a798-3c3a-4d30-b931-fdbc2383b3fb)

2024-09-20 20:06 UTC, mlm483 approved these changes

2024-09-24 13:24 UTC, davedrp commented
> @davedrp Don't you need a Germplasm entry before you can do a Experiments and Observation? ![image](https://private-user-images.githubusercontent.com/15913865/369274732-3f22a798-3c3a-4d30-b931-fdbc2383b3fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODQ0MzYsIm5iZiI6MTcyNzE4NDEzNiwicGF0aCI6Ii8xNTkxMzg2NS8zNjkyNzQ3MzItM2YyMmE3OTgtM2MzYS00ZDMwLWI5MzEtZmRiYzIzODNiM2ZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEzMjIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MmFmMDMzMGQyZDdjMDMwMWJhMGI4ZmRjNjMyMTZmY2JiYjU3NTJlYzVmZTQ1YjJmMGU3OGYwOTc3YzIwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.47HRtp7KHV7NryVEUe9dhDSWCs5XvH_s5ut2CyX_HHY)

@cvacalares You are correct.  You do.

2024-09-24 13:25 UTC, davedrp approved these changes

2024-09-24 23:52 UTC, merged