Feature/bi 2388
Breeding-Insight/taf pull request #157
Opened 2024-12-28 23:47 UTC by cvacalares

# Description
BI-2388 - Sys admin permission.

# Testing
[_Please include a link to a successful run of TAF for this change_
](https://github.com/Breeding-Insight/taf/actions/runs/12522422735)

# Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation

2025-01-06 15:00 UTC, nickpalladino requested changes

2025-01-06 15:00 UTC, nickpalladino commented on src/features/BI-2388.feature
> +    When user selects "Germplas" in top-level navigation
Missing the trailing 'm' on Germplasm

2025-01-10 06:32 UTC, cvacalares commented on src/features/BI-2388.feature
> +    When user selects "Germplas" in top-level navigation
Done.

2025-01-10 15:08 UTC, nickpalladino approved these changes

2025-01-13 14:12 UTC, davedrp approved these changes
Test pased

2025-01-14 06:25 UTC, merged