Feature/bi 1502
Breeding-Insight/taf pull request #86
Opened 2022-09-19 05:41 UTC by cvacalares

# Description
BI-1502 - Shared Ontology testing

# Dependencies
None

# Testing
[_Please include a link to a successful run of TAF for this change_](https://github.com/Breeding-Insight/taf/actions/runs/3071844282)

# Checklist:

- [x ] I have performed a self-review of my own code
- [ ] I have tested my code and ensured it meets the acceptance criteria of the story
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to documentation

2022-09-22 18:06 UTC, nickpalladino approved these changes

2022-09-23 19:01 UTC, timparsons requested changes
A few small readability and future-proofing suggestions

2022-09-24 06:07 UTC, cvacalares commented on src/step_definitions/programManagementSteps.js
> +    await page.section.programManagement.click("@configurationLink");
Done

2022-09-24 23:29 UTC, cvacalares commented on src/step_definitions/programManagementSteps.js
> +  /^user can see "([^"]*)" section on Program Management page$/,
Done

2022-09-24 23:29 UTC, cvacalares commented on src/step_definitions/programManagementSteps.js
> +    await page.section.configurationForm.assert.visible(
Done

2022-09-24 23:29 UTC, cvacalares commented on src/step_definitions/programManagementSteps.js
> +    await page.section.configurationForm.assert.containsText(
Done

2022-10-04 00:15 UTC, cvacalares commented
Test run of changes at https://github.com/Breeding-Insight/taf/actions/runs/3171605326.
Please review.
@timparsons

2022-10-04 13:50 UTC, timparsons approved these changes

2022-10-09 00:06 UTC, merged